// SPDX-License-Identifier: GPL-3.0-or-later
//! Generates compact, version-pinned NFC tables from ADR-0029 UCD inputs.

use std::{
    collections::{BTreeMap, BTreeSet},
    env, fs,
    path::PathBuf,
};

fn hex(value: &str) -> u32 {
    u32::from_str_radix(value, 16).expect("UCD hex")
}
fn range(value: &str) -> Vec<u32> {
    let mut parts = value.trim().split("..");
    let start = hex(parts.next().expect("range start"));
    match parts.next() {
        Some(end) => (start..=hex(end)).collect(),
        None => vec![start],
    }
}

fn main() {
    let root = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest"));
    let ucd = root.join("unicode/ucd-17.0.0");
    for file in [
        "UnicodeData.txt",
        "DerivedNormalizationProps.txt",
        "CompositionExclusions.txt",
    ] {
        println!("cargo:rerun-if-changed={}", ucd.join(file).display());
    }
    let exclusions: BTreeSet<u32> = fs::read_to_string(ucd.join("DerivedNormalizationProps.txt"))
        .expect("UCD props")
        .lines()
        .filter_map(|line| {
            let line = line.split('#').next()?.trim();
            let (points, prop) = line.split_once(';')?;
            (prop.trim() == "Full_Composition_Exclusion").then(|| range(points))
        })
        .flatten()
        .collect();
    let mut decompositions = BTreeMap::<u32, Vec<u32>>::new();
    let mut ccc = BTreeMap::<u32, u8>::new();
    for line in fs::read_to_string(ucd.join("UnicodeData.txt"))
        .expect("UCD data")
        .lines()
    {
        let fields: Vec<_> = line.split(';').collect();
        if fields.len() != 15 || fields[1].ends_with(", First>") || fields[1].ends_with(", Last>") {
            continue;
        }
        let cp = hex(fields[0]);
        let class: u8 = fields[3].parse().expect("canonical combining class");
        if class != 0 {
            ccc.insert(cp, class);
        }
        let mapping = fields[5];
        if !mapping.is_empty() && !mapping.starts_with('<') {
            let values: Vec<_> = mapping.split_whitespace().map(hex).collect();
            assert!(values.len() <= 2, "UCD canonical mapping length");
            decompositions.insert(cp, values);
        }
    }
    let mut compositions = BTreeMap::<(u32, u32), u32>::new();
    for (&cp, mapping) in &decompositions {
        if mapping.len() == 2 && !exclusions.contains(&cp) && !ccc.contains_key(&mapping[0]) {
            compositions.insert((mapping[0], mapping[1]), cp);
        }
    }
    let mut out = String::from("// SPDX-License-Identifier: Unicode-3.0\n// Generated by tos-core-unicode-gen/1 from UCD 17.0.0.\n");
    out.push_str("pub static DECOMP: &[(u32, u32, u32)] = &[\n");
    for (cp, values) in decompositions {
        out.push_str(&format!(
            "({cp}, {}, {}),\n",
            values[0],
            values.get(1).copied().unwrap_or(0)
        ));
    }
    out.push_str("];\npub static CCC: &[(u32, u8)] = &[\n");
    for (cp, value) in ccc {
        out.push_str(&format!("({cp}, {value}),\n"));
    }
    out.push_str("];\npub static COMPOSE: &[(u32, u32, u32)] = &[\n");
    for ((a, b), cp) in compositions {
        out.push_str(&format!("({a}, {b}, {cp}),\n"));
    }
    out.push_str("];\n");
    fs::write(
        PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("unicode_tables.rs"),
        out,
    )
    .expect("generated tables");
}
