// SPDX-License-Identifier: GPL-3.0-or-later
//! Host integration tests for the capsule format v1.
//!
//! Golden vectors live in `tests/vectors/capsule-v1/` (committed binaries,
//! regenerated by `host-tools/capsule`; see the README there). Each vector is
//! embedded at compile time and must produce exactly the documented outcome.

#![cfg(test)]

use tos_capsule::{CapsError, parse, FLAG_BOOT_CANONICAL};
use tos_hash::sha256;

const V: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/capsule-v1/");

fn vec(name: &str) -> Vec<u8> {
    std::fs::read(format!("{V}{name}")).expect("read vector")
}

#[test]
fn golden_valid_parses() {
    let bytes = vec("valid-001.bin");
    let cap = parse(&bytes).expect("valid vector must parse");
    assert_eq!(cap.file_count(), 2);
    let boot = cap.boot_file().expect("boot file");
    assert!(boot.flags & FLAG_BOOT_CANONICAL != 0);
    assert_eq!(boot.name, b"/system/boot/init.tos");
    let v = cap.find(b"/system/version").expect("version file");
    assert_eq!(v.content, b"0.2.1\n");
}

#[test]
fn golden_valid_whole_digest_self_consistent() {
    let bytes = vec("valid-001.bin");
    let cap = parse(&bytes).unwrap();
    let h = cap.header();
    // The whole-capsule digest is over bytes[0..152] || zeros[32] || bytes[184..].
    let mut hh = tos_hash::Sha256::new();
    hh.update(&bytes[0..152]);
    hh.update(&[0u8; 32]);
    hh.update(&bytes[184..]);
    assert_eq!(hh.finalize(), h.whole_capsule_digest);
}

#[test]
fn golden_invalid_vectors_rejected() {
    let cases: &[(&str, CapsError)] = &[
        ("invalid-badmagic.bin", CapsError::BadMagic),
        ("invalid-truncated.bin", CapsError::TotalLengthMismatch),
        ("invalid-missing-boot.bin", CapsError::MissingBootCanonical),
        ("invalid-traversal.bin", CapsError::TraversalInPath),
        ("invalid-dup.bin", CapsError::DuplicatePath),
        ("invalid-kind-none.bin", CapsError::UnsupportedIdentityKind),
    ];
    for (name, err) in cases {
        let bytes = vec(name);
        assert_eq!(parse(&bytes), Err(*err), "vector {name}");
    }
}

#[test]
fn deterministic_build_reproduces_golden() {
    // Rebuilding the same files must reproduce the committed golden vector
    // byte-for-byte (this pins the whole format).
    let mut b = tos_capsule::build::Builder::new();
    b.source_identity_digest = [0x42; 32];
    b.add(tos_capsule::build::FileSpec::new(
        "/system/boot/init.tos",
        b"# TOS boot text\nprint(\"hello from boot\")\n",
    ));
    b.add(tos_capsule::build::FileSpec::new("/system/version", b"0.2.1\n"));
    let rebuilt = b.build().expect("build");
    let golden = vec("valid-001.bin");
    assert_eq!(rebuilt, golden, "builder must reproduce the golden vector");
    assert_eq!(
        sha256(&rebuilt),
        sha256(&golden),
        "digest must match"
    );
}

#[test]
fn tamper_suite() {
    // Flip every single byte of a valid capsule; each mutation must be
    // rejected (never accepted, never panicking).
    let base = vec("valid-001.bin");
    for i in 0..base.len() {
        let mut m = base.clone();
        m[i] ^= 0xff;
        let r = parse(&m);
        assert!(r.is_err(), "byte {i} flip must be rejected");
    }
}

#[test]
fn truncation_prefix_suite() {
    let base = vec("valid-001.bin");
    for cut in 0..base.len() {
        let r = parse(&base[..cut]);
        assert!(r.is_err(), "prefix cut {cut} must be rejected");
    }
}

#[test]
fn perf_smoke_1000_files() {
    // docs/35 budget: 1000 files / 16 MiB validated in <= 250 ms p95 on the
    // CI profile. This is a smoke bound (10x slack) to catch pathological
    // regressions on dev machines; the real measurement is the QEMU log.
    let mut b = tos_capsule::build::Builder::new();
    b.source_identity_digest = [0x33; 32];
    b.add(tos_capsule::build::FileSpec::new(
        "/system/boot/init.tos",
        b"# boot\n",
    ));
    for i in 0..1000 {
        b.add(tos_capsule::build::FileSpec::new(
            &format!("/system/lib/file{i:05}.tos"),
            &vec![0xabu8; 16800],
        ));
    }
    let bytes = b.build().expect("build");
    assert!(
        bytes.len() >= 16 * 1024 * 1024,
        "payload under the 16 MiB contract size"
    );

    let t0 = std::time::Instant::now();
    let cap = parse(&bytes).expect("parse 1000 files");
    let dt = t0.elapsed();
    assert_eq!(cap.file_count(), 1001);
    // `cargo test` compiles in debug (unoptimised), so this smoke bound is very
    // lenient. The real 250 ms p95 contract is measured on the release build
    // and printed by the QEMU harness (host-tools/qemu-run). This test only
    // catches pathological super-linear regressions.
    assert!(
        dt.as_millis() < 15_000,
        "parse of 1000 files / 16 MiB took {} ms in debug",
        dt.as_millis()
    );
    eprintln!(
        "perf_smoke: 1000 files / 16 MiB parsed in {:?} (debug build)",
        dt
    );
}

#[test]
fn boot_protocol_struct_sizes() {
    assert_eq!(core::mem::size_of::<tos_boot_protocol::BootInfo>(), 224);
    assert_eq!(core::mem::size_of::<tos_boot_protocol::MemoryRange>(), 24);
}
