// SPDX-License-Identifier: GPL-3.0-or-later
//! Host integration tests for the capsule format v1.
//!
//! Golden vectors live in `tests/vectors/capsule-v1/` (committed binaries,
//! regenerated by `tests/vectors/gen/gen.sh`). Each vector is embedded at
//! compile time and must produce exactly the documented outcome. The golden
//! capsule is built from the REAL `system/boot/init.tos` and `NOTICES.txt`
//! (licence tail); the builder must reproduce it byte-for-byte.

#![cfg(test)]

use tos_capsule::{parse, FLAG_BOOT_CANONICAL, SRC_KIND_DETACHED};
use tos_hash::sha256;

const V: &str = concat!(env!("CARGO_MANIFEST_DIR"), "/../vectors/capsule-v1/");
// Real sources (up two levels from tests/integration -> source/).
const INIT_TOS: &[u8] = include_bytes!("../../../system/boot/init.tos");
const NOTICES: &[u8] = include_bytes!("../../../system/boot/NOTICES.txt");

fn vec(name: &str) -> Vec<u8> {
    std::fs::read(format!("{V}{name}")).expect("read vector")
}

#[test]
fn golden_valid_parses() {
    let bytes = vec("valid-001.bin");
    let cap = parse(&bytes).expect("valid vector must parse");
    assert_eq!(cap.file_count(), 2);
    let boot = cap.boot_file().expect("boot file");
    assert!(boot.flags & FLAG_BOOT_CANONICAL != 0);
    assert_eq!(boot.name, b"/system/boot/init.tos");
    assert_eq!(
        boot.content, INIT_TOS,
        "boot text must be the real init.tos"
    );
    let v = cap.find(b"/system/version").expect("version file");
    assert_eq!(v.content, b"0.2.1\n");
    // licence tail is the real NOTICES.txt
    let h = cap.header();
    let second_content_offset_at = h.file_table_offset as usize + 64;
    let second_content_offset = u64::from_le_bytes(
        bytes[second_content_offset_at..second_content_offset_at + 8]
            .try_into()
            .expect("second content offset"),
    );
    assert_ne!(
        second_content_offset % 8,
        0,
        "fixture must exercise unaligned content"
    );
    assert!(
        parse(&bytes).is_ok(),
        "canonical unaligned capsule must parse"
    );
    assert!(h.licence_notice_length as usize == NOTICES.len());
    assert_eq!(
        &bytes[h.licence_notice_offset as usize..],
        NOTICES,
        "licence tail must be the real NOTICES.txt"
    );
}

#[test]
fn golden_valid_whole_digest_self_consistent() {
    let bytes = vec("valid-001.bin");
    let cap = parse(&bytes).unwrap();
    let h = cap.header();
    // The whole-capsule digest is over bytes[0..152] || zeros[32] || bytes[184..].
    let mut hh = tos_hash::Sha256::new();
    hh.update(&bytes[0..152]);
    hh.update(&[0u8; 32]);
    hh.update(&bytes[184..]);
    assert_eq!(hh.finalize(), h.whole_capsule_digest);
}

/// Parse `vectors.tsv` (CAPSULE_FORMAT_V1.md §10) into (file, outcome) rows.
/// The table is the committed expectation; the test is driven by it rather than
/// by a list duplicated in Rust.
fn vector_table() -> Vec<(String, String)> {
    let text = std::fs::read_to_string(format!("{V}vectors.tsv")).expect("read vectors.tsv");
    text.lines()
        .map(str::trim)
        .filter(|l| !l.is_empty() && !l.starts_with('#'))
        .map(|l| {
            let (name, outcome) = l.split_once('\t').expect("vectors.tsv is tab-separated");
            (name.trim().to_string(), outcome.trim().to_string())
        })
        .collect()
}

#[test]
fn every_vector_matches_its_declared_outcome() {
    let rows = vector_table();
    assert!(!rows.is_empty(), "vectors.tsv is empty");
    for (name, outcome) in &rows {
        let bytes = vec(name);
        let got = parse(&bytes);
        match outcome.as_str() {
            "accept" => {
                got.unwrap_or_else(|e| panic!("vector {name}: expected accept, got {e:?}"));
            }
            other => {
                let want = other
                    .strip_prefix("reject:")
                    .unwrap_or_else(|| panic!("vector {name}: bad outcome {other:?}"));
                // Compare the Debug name so the table stays readable and does
                // not have to be kept in sync with a Rust match arm.
                let err = got.err().unwrap_or_else(|| {
                    panic!("vector {name}: expected reject:{want}, but it parsed")
                });
                assert_eq!(format!("{err:?}"), want, "vector {name}");
            }
        }
    }
}

#[test]
fn vector_table_covers_every_committed_fixture() {
    // A fixture that nobody declares would be silently untested; a declared
    // fixture that no longer exists would make the table lie.
    let declared: std::collections::BTreeSet<String> =
        vector_table().into_iter().map(|(n, _)| n).collect();
    let present: std::collections::BTreeSet<String> = std::fs::read_dir(V)
        .expect("read vector dir")
        .map(|e| {
            e.expect("dir entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|n| n.ends_with(".bin"))
        .collect();
    assert_eq!(declared, present, "vectors.tsv and *.bin disagree");
}

#[test]
fn deterministic_build_reproduces_golden() {
    // Rebuilding the same real files must reproduce the committed golden
    // vector byte-for-byte (this pins the whole format).
    let mut b = tos_capsule::build::Builder::new();
    b.source_identity_kind = SRC_KIND_DETACHED;
    b.source_identity_value = [0x42; 32];
    b.add(tos_capsule::build::FileSpec::new(
        "/system/boot/init.tos",
        INIT_TOS,
    ));
    b.add(tos_capsule::build::FileSpec::new(
        "/system/version",
        b"0.2.1\n",
    ));
    b.set_licence_notice(NOTICES.to_vec());
    let rebuilt = b.build().expect("build");
    let golden = vec("valid-001.bin");
    assert_eq!(rebuilt, golden, "builder must reproduce the golden vector");
    assert_eq!(sha256(&rebuilt), sha256(&golden), "digest must match");
}

#[test]
fn tamper_suite() {
    // Flip every single byte of a valid capsule; each mutation must be
    // rejected (never accepted, never panicking).
    let base = vec("valid-001.bin");
    for i in 0..base.len() {
        let mut m = base.clone();
        m[i] ^= 0xff;
        let r = parse(&m);
        assert!(r.is_err(), "byte {i} flip must be rejected");
    }
}

#[test]
fn truncation_prefix_suite() {
    let base = vec("valid-001.bin");
    for cut in 0..base.len() {
        let r = parse(&base[..cut]);
        assert!(r.is_err(), "prefix cut {cut} must be rejected");
    }
}

#[test]
fn perf_smoke_1000_files() {
    // docs/35 budget: 1000 files / 16 MiB validated in <= 250 ms p95 on the
    // CI profile. This is a smoke bound (10x slack) to catch pathological
    // regressions on dev machines; the real measurement is the QEMU log.
    let mut b = tos_capsule::build::Builder::new();
    b.source_identity_value = [0x33; 32];
    b.add(tos_capsule::build::FileSpec::new(
        "/system/boot/init.tos",
        b"# boot\n",
    ));
    for i in 0..1000 {
        b.add(tos_capsule::build::FileSpec::new(
            &format!("/system/lib/file{i:05}.tos"),
            &vec![0xabu8; 16800],
        ));
    }
    let bytes = b.build().expect("build");
    assert!(
        bytes.len() >= 16 * 1024 * 1024,
        "payload under the 16 MiB contract size"
    );

    let t0 = std::time::Instant::now();
    let cap = parse(&bytes).expect("parse 1000 files");
    let dt = t0.elapsed();
    assert_eq!(cap.file_count(), 1001);
    // `cargo test` compiles in debug (unoptimised), so this smoke bound is very
    // lenient. The real 250 ms p95 contract is measured on the release build
    // and printed by the QEMU harness (host-tools/qemu-run). This test only
    // catches pathological super-linear regressions.
    assert!(
        dt.as_millis() < 15_000,
        "parse of 1000 files / 16 MiB took {} ms in debug",
        dt.as_millis()
    );
    eprintln!(
        "perf_smoke: 1000 files / 16 MiB parsed in {:?} (debug build)",
        dt
    );
}

#[test]
fn boot_protocol_struct_sizes() {
    assert_eq!(core::mem::size_of::<tos_boot_protocol::BootInfo>(), 224);
    assert_eq!(core::mem::size_of::<tos_boot_protocol::MemoryRange>(), 24);
}
