// SPDX-License-Identifier: GPL-3.0-or-later
//! Emits the predeclared contract's content digests for this build.
//!
//! `docs/43` §5 permits the independent verifier to consume a shared
//! declarative table **only if its content digest is input to both
//! components**. This is that input, on the verifier's side: the digest of the
//! table this build actually links against is computed here and compared, in
//! the verifier's own source, against the digests the verifier states it was
//! written for. The comparison is a `const` assertion, so a table edited under
//! this component fails its compilation rather than its test suite.
//!
//! The script computes; it decides nothing. The accepted values live in
//! `src/lib.rs` where a reader of the verifier can see them.

use std::{env, fs, path::PathBuf};

fn main() {
    let table = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest"))
        .join("../tos-predeclared/src/lib.rs");
    println!("cargo:rerun-if-changed={}", table.display());
    let mut out = String::from(
        "// Generated by tos-verifier's build script from the linked tos-predeclared.\n\
         pub(crate) const LINKED_PREDECLARED_DIGESTS: [(u32, &str); 5] = [\n",
    );
    for minor in 0..=4u32 {
        let contract = tos_predeclared::Contract::at_minor(minor);
        let hex = tos_predeclared::hex_digest(&contract);
        let hex = std::str::from_utf8(&hex).expect("hex is ASCII");
        out.push_str(&format!("    ({minor}, \"{hex}\"),\n"));
    }
    out.push_str("];\n");
    fs::write(
        PathBuf::from(env::var("OUT_DIR").expect("out dir")).join("predeclared_digests.rs"),
        out,
    )
    .expect("generated digests");
}
