// SPDX-License-Identifier: GPL-3.0-or-later
//! A compact derived view of a module, sufficient for set-wide resolution.
//!
//! Resolution across a source set compares every module's declared name,
//! imports and type surface against every other's. Doing that over parse trees
//! means every module of a dependency closure is live at once, and a parse tree
//! costs roughly fifty times its source — so the memory a closure needs grows
//! linearly in the closure with a very large constant. Measured, that is about
//! 3.2 GiB for the largest closure the two published ceilings admit together,
//! which is not an architecture a reference and recovery frontend should rest
//! on.
//!
//! A summary is what resolution actually reads: a name, a path, a content
//! identity, the imports, the declared type names, and the qualified type names
//! this module uses. Everything else the parse tree holds — statements,
//! expressions, bodies — resolution never looks at. So a loader parses one
//! module, summarizes it, drops the tree, and resolves over the summaries.
//!
//! **Derived, never authoritative.** Canonical source is the truth. A summary is
//! regenerated by parsing, and deleting every summary in existence costs time
//! and nothing else. Nothing here is a cache format, and no summary is admitted
//! on its own word: [`ModuleSummary::content_id`] is the digest of the
//! normalized source it was derived from, and [`ModuleSummary::describes`] is
//! how a caller that did not just derive it checks that it belongs to the
//! source in hand.
//!
//! **Diagnostics survive the tree.** A diagnostic needs a byte span *and* the
//! line and column derived from it, and the derivation needs the source. So a
//! summary carries the positions already derived, taken at the moment the
//! source was in hand. That is the one thing that would otherwise force the
//! source to be retained.

use alloc::string::{String, ToString};
use alloc::vec::Vec;

use crate::parser::{ImportKind, Schema, Span};
use crate::{Position, SourceUnit};

/// A span with the positions already derived from its source.
///
/// Deriving a line and column needs the source text. Carrying the derived
/// positions is what lets a diagnostic be built after the source is gone,
/// without either retaining the source or reporting a position nobody computed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Located {
    pub span: Span,
    pub start: Position,
    pub end: Position,
}

impl Located {
    pub fn of(source: &SourceUnit, span: Span) -> Located {
        Located {
            span,
            start: Position::at(source, span.start()),
            end: Position::at(source, span.end()),
        }
    }
}

/// One import, as resolution needs it.
#[derive(Clone, Debug)]
pub struct ImportSummary {
    pub kind: ImportKind,
    /// The dotted module path the import names.
    pub target: String,
    /// The local binding the import introduces.
    pub binding: String,
    pub at: Located,
}

/// The type names a module declares, held as bytes rather than as strings.
///
/// **One question, asked once per qualified use**: does this module declare this
/// name. Everything else a set of `String`s would carry — a node per name, a
/// pointer, a length, a capacity, an allocation — is cost, and it is the cost
/// that decides how large a build workspace has to be. Measured at the docs/44
/// source ceiling, a `BTreeSet<String>` spent about `90 B` per name on a name
/// averaging under `7 B`; this spends the name's bytes and four more
/// (`docs/evidence/STAGE3_BUILD_WORKSPACE.md`).
///
/// The names are sorted and deduplicated at construction, so membership is a
/// binary search over one contiguous buffer. Comparison is over the bytes
/// themselves — there is no digest here and no collision to reason about, which
/// is why this is a representation change and not a semantic one.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct TypeNames {
    /// Every name, sorted, end to end.
    text: Vec<u8>,
    /// Where each name starts, plus a terminator, so a name runs from its own
    /// offset to the next.
    offsets: Vec<u32>,
}

impl TypeNames {
    /// Packs what the frontend found, sorted and deduplicated.
    pub fn of<'a>(names: impl IntoIterator<Item = &'a str>) -> TypeNames {
        let mut sorted: Vec<&str> = names.into_iter().collect();
        sorted.sort_unstable();
        sorted.dedup();
        let mut text = Vec::with_capacity(sorted.iter().map(|name| name.len()).sum());
        let mut offsets = Vec::with_capacity(sorted.len() + 1);
        for name in sorted {
            offsets.push(text.len() as u32);
            text.extend_from_slice(name.as_bytes());
        }
        offsets.push(text.len() as u32);
        TypeNames { text, offsets }
    }

    /// Whether this module declares that name.
    pub fn contains(&self, name: &str) -> bool {
        let count = self.len();
        let mut low = 0usize;
        let mut high = count;
        while low < high {
            let middle = (low + high) / 2;
            match self.at(middle).as_bytes().cmp(name.as_bytes()) {
                core::cmp::Ordering::Less => low = middle + 1,
                core::cmp::Ordering::Greater => high = middle,
                core::cmp::Ordering::Equal => return true,
            }
        }
        false
    }

    pub fn len(&self) -> usize {
        self.offsets.len().saturating_sub(1)
    }

    pub fn is_empty(&self) -> bool {
        self.len() == 0
    }

    /// The name at a position, in sorted order.
    pub fn at(&self, position: usize) -> &str {
        let start = self.offsets[position] as usize;
        let end = self.offsets[position + 1] as usize;
        // The buffer is built from `&str`s and is only ever appended to whole
        // names, so every span is valid text. `unwrap_or` keeps the function
        // total rather than proving it.
        core::str::from_utf8(&self.text[start..end]).unwrap_or("")
    }

    /// Every name, in sorted order.
    pub fn iter(&self) -> impl Iterator<Item = &str> {
        (0..self.len()).map(|position| self.at(position))
    }

    /// What this costs, for a caller measuring a build's account.
    pub fn retained_bytes(&self) -> usize {
        core::mem::size_of::<TypeNames>() + self.text.capacity() + self.offsets.capacity() * 4
    }
}

/// One qualified type name this module writes, e.g. `up.Reading`.
#[derive(Clone, Debug)]
pub struct QualifiedUse {
    /// The import binding the name is qualified by.
    pub binding: String,
    /// The type name after the binding.
    pub name: String,
    /// The whole name as written, for the diagnostic.
    pub spelled: String,
    pub at: Located,
}

/// Everything set-wide resolution reads about one module.
///
/// It is bounded by the module's *interface*, not by its body: a module with
/// ten thousand statements and three imports summarizes to the same size as one
/// with three statements and three imports.
#[derive(Clone, Debug)]
pub struct ModuleSummary {
    /// Canonical repository path, relative to the declared module root.
    pub path: String,
    /// Position in the declared ordered root list; earlier roots win.
    pub root: usize,
    /// The declared dependency source set this came from, or `None` for local.
    pub dependency_set: Option<String>,
    /// The module name its header declares, dot-separated.
    pub name: String,
    /// The header span, which an identity finding points at.
    pub header: Located,
    /// `sha256:<hex>` of the normalized source this was derived from.
    pub content_id: String,
    pub imports: Vec<ImportSummary>,
    /// Every type name this module declares, for a qualified name to resolve.
    pub declared_types: TypeNames,
    /// Every qualified type name this module writes.
    pub qualified_uses: Vec<QualifiedUse>,
}

impl ModuleSummary {
    /// Derives a summary from a parsed module.
    ///
    /// The tree may be dropped as soon as this returns: nothing the summary
    /// holds borrows it.
    pub fn derive(
        path: &str,
        root: usize,
        dependency_set: Option<&str>,
        source: &SourceUnit,
        schema: &Schema,
    ) -> ModuleSummary {
        ModuleSummary::derived(path, root, dependency_set, source, schema, true)
    }

    /// The same, without the qualified uses.
    ///
    /// For a first pass that will read them again: a module's uses are read by
    /// exactly one check, and a caller that intends to enumerate them in a
    /// second pass should not be paying to hold them in between. What is left
    /// is what a set is resolved *from* — the name, the path, the identity, the
    /// imports and the type surface.
    pub fn derive_membership(
        path: &str,
        root: usize,
        dependency_set: Option<&str>,
        source: &SourceUnit,
        schema: &Schema,
    ) -> ModuleSummary {
        ModuleSummary::derived(path, root, dependency_set, source, schema, false)
    }

    fn derived(
        path: &str,
        root: usize,
        dependency_set: Option<&str>,
        source: &SourceUnit,
        schema: &Schema,
        with_uses: bool,
    ) -> ModuleSummary {
        let prefix = schema.outline().prefix();
        let header = prefix.header();
        let name = header
            .name()
            .iter()
            .map(|segment| segment.text(source))
            .collect::<Vec<_>>()
            .join(".");

        let imports = prefix
            .imports()
            .iter()
            .map(|import| ImportSummary {
                kind: import.kind(),
                target: import
                    .path()
                    .iter()
                    .map(|segment| segment.text(source))
                    .collect::<Vec<_>>()
                    .join("."),
                binding: import.binding().text(source).to_string(),
                at: Located::of(source, import.span()),
            })
            .collect();

        let declared_types = TypeNames::of(crate::types::declared_type_names(source, schema));

        let qualified_uses = if with_uses {
            crate::types::qualified_type_uses(source, schema)
                .into_iter()
                .map(|(binding, name, span)| QualifiedUse {
                    binding: binding.to_string(),
                    name: name.to_string(),
                    spelled: span.text(source).to_string(),
                    at: Located::of(source, span),
                })
                .collect()
        } else {
            Vec::new()
        };

        ModuleSummary {
            path: path.to_string(),
            root,
            dependency_set: dependency_set.map(ToString::to_string),
            name,
            header: Located::of(source, header.span()),
            content_id: content_id(source.bytes()),
            imports,
            declared_types,
            qualified_uses,
        }
    }

    /// Whether this summary was derived from exactly these source bytes.
    ///
    /// A resolver handed a summary it did not derive must ask. A summary is a
    /// derived artifact, and a derived artifact that is trusted without being
    /// bound to its input is a way to make the source stop being the truth.
    pub fn describes(&self, bytes: &[u8]) -> bool {
        self.content_id == content_id(bytes)
    }

    /// The identity every diagnostic about this module carries.
    pub fn identity(&self) -> crate::ModuleIdentity {
        crate::ModuleIdentity::new(
            self.name.clone(),
            self.path.clone(),
            self.content_id.clone(),
        )
    }

    /// The module-set imports, which name modules rather than capabilities.
    pub fn module_imports(&self) -> impl Iterator<Item = &ImportSummary> {
        self.imports
            .iter()
            .filter(|import| import.kind != ImportKind::Capability)
    }

    /// Reduces a checked summary to what building a closure still reads.
    ///
    /// Consuming, and that is the point: a build that could hold both would
    /// hold both.
    pub fn into_plan(self) -> ModulePlan {
        let imports = self
            .imports
            .into_iter()
            .filter(|import| import.kind != ImportKind::Capability)
            .map(|import| import.target)
            .collect();
        ModulePlan {
            path: self.path,
            name: self.name,
            content_id: self.content_id,
            imports,
        }
    }
}

/// What a build still reads about a module once the set has been checked.
///
/// **A summary answers set-wide questions, and they are asked once.** Whether
/// every import resolves, whether a qualified type name exists in the module its
/// binding names, whether the path is the one the name derives — all of that is
/// [`check_module_summaries`](crate::check_module_summaries), and nothing asks
/// again. What the rest of a build needs is narrower: which modules the entry
/// reaches, in what order, under which identities.
///
/// The difference is not small. At the docs/44 source ceiling a summary is about
/// `208 KiB` — a module declaring thousands of types carries every one of those
/// names so that another module's qualified use can be resolved against it — and
/// a plan is a few hundred bytes. At the closure ceiling that made the summaries
/// the build workspace's largest single owner at `52.1 MiB`
/// (`docs/evidence/STAGE3_BUILD_WORKSPACE.md`).
///
/// This is a type rather than a convention because a convention would be
/// followed until it wasn't: a plan **cannot** carry a type surface, since it has
/// no field for one.
#[derive(Clone, Debug)]
pub struct ModulePlan {
    /// Canonical repository path, relative to the declared module root.
    pub path: String,
    /// The module name its header declares, dot-separated.
    pub name: String,
    /// `sha256:<hex>` of the normalized source this was derived from.
    pub content_id: String,
    /// The modules this one imports, in source order, by declared name.
    ///
    /// Module imports only: a capability import names an interface rather than
    /// a member of the closure, and a closure walk that followed one would be
    /// looking for a module nobody wrote.
    pub imports: Vec<String>,
}

/// `sha256:<hex>` over the normalized source bytes.
fn content_id(bytes: &[u8]) -> String {
    let digest = tos_hash::sha256(bytes);
    let mut hex = [0u8; 64];
    tos_hash::hex(&digest, &mut hex);
    alloc::format!(
        "sha256:{}",
        core::str::from_utf8(&hex).expect("hex output is ASCII")
    )
}
