// SPDX-License-Identifier: GPL-3.0-or-later
//! A compact derived view of a module, sufficient for set-wide resolution.
//!
//! Resolution across a source set compares every module's declared name,
//! imports and type surface against every other's. Doing that over parse trees
//! means every module of a dependency closure is live at once, and a parse tree
//! costs roughly fifty times its source — so the memory a closure needs grows
//! linearly in the closure with a very large constant. Measured, that is about
//! 3.2 GiB for the largest closure the two published ceilings admit together,
//! which is not an architecture a reference and recovery frontend should rest
//! on.
//!
//! A summary is what resolution actually reads: a name, a path, a content
//! identity, the imports, the declared type names, and the qualified type names
//! this module uses. Everything else the parse tree holds — statements,
//! expressions, bodies — resolution never looks at. So a loader parses one
//! module, summarizes it, drops the tree, and resolves over the summaries.
//!
//! **Derived, never authoritative.** Canonical source is the truth. A summary is
//! regenerated by parsing, and deleting every summary in existence costs time
//! and nothing else. Nothing here is a cache format, and no summary is admitted
//! on its own word: [`ModuleSummary::content_id`] is the digest of the
//! normalized source it was derived from, and [`ModuleSummary::describes`] is
//! how a caller that did not just derive it checks that it belongs to the
//! source in hand.
//!
//! **Diagnostics survive the tree.** A diagnostic needs a byte span *and* the
//! line and column derived from it, and the derivation needs the source. So a
//! summary carries the positions already derived, taken at the moment the
//! source was in hand. That is the one thing that would otherwise force the
//! source to be retained.

use alloc::collections::BTreeSet;
use alloc::string::{String, ToString};
use alloc::vec::Vec;

use crate::parser::{ImportKind, Schema, Span};
use crate::{Position, SourceUnit};

/// A span with the positions already derived from its source.
///
/// Deriving a line and column needs the source text. Carrying the derived
/// positions is what lets a diagnostic be built after the source is gone,
/// without either retaining the source or reporting a position nobody computed.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct Located {
    pub span: Span,
    pub start: Position,
    pub end: Position,
}

impl Located {
    pub fn of(source: &SourceUnit, span: Span) -> Located {
        Located {
            span,
            start: Position::at(source, span.start()),
            end: Position::at(source, span.end()),
        }
    }
}

/// One import, as resolution needs it.
#[derive(Clone, Debug)]
pub struct ImportSummary {
    pub kind: ImportKind,
    /// The dotted module path the import names.
    pub target: String,
    /// The local binding the import introduces.
    pub binding: String,
    pub at: Located,
}

/// One qualified type name this module writes, e.g. `up.Reading`.
#[derive(Clone, Debug)]
pub struct QualifiedUse {
    /// The import binding the name is qualified by.
    pub binding: String,
    /// The type name after the binding.
    pub name: String,
    /// The whole name as written, for the diagnostic.
    pub spelled: String,
    pub at: Located,
}

/// Everything set-wide resolution reads about one module.
///
/// It is bounded by the module's *interface*, not by its body: a module with
/// ten thousand statements and three imports summarizes to the same size as one
/// with three statements and three imports.
#[derive(Clone, Debug)]
pub struct ModuleSummary {
    /// Canonical repository path, relative to the declared module root.
    pub path: String,
    /// Position in the declared ordered root list; earlier roots win.
    pub root: usize,
    /// The declared dependency source set this came from, or `None` for local.
    pub dependency_set: Option<String>,
    /// The module name its header declares, dot-separated.
    pub name: String,
    /// The header span, which an identity finding points at.
    pub header: Located,
    /// `sha256:<hex>` of the normalized source this was derived from.
    pub content_id: String,
    pub imports: Vec<ImportSummary>,
    /// Every type name this module declares, for a qualified name to resolve.
    pub declared_types: BTreeSet<String>,
    /// Every qualified type name this module writes.
    pub qualified_uses: Vec<QualifiedUse>,
}

impl ModuleSummary {
    /// Derives a summary from a parsed module.
    ///
    /// The tree may be dropped as soon as this returns: nothing the summary
    /// holds borrows it.
    pub fn derive(
        path: &str,
        root: usize,
        dependency_set: Option<&str>,
        source: &SourceUnit,
        schema: &Schema,
    ) -> ModuleSummary {
        let prefix = schema.outline().prefix();
        let header = prefix.header();
        let name = header
            .name()
            .iter()
            .map(|segment| segment.text(source))
            .collect::<Vec<_>>()
            .join(".");

        let imports = prefix
            .imports()
            .iter()
            .map(|import| ImportSummary {
                kind: import.kind(),
                target: import
                    .path()
                    .iter()
                    .map(|segment| segment.text(source))
                    .collect::<Vec<_>>()
                    .join("."),
                binding: import.binding().text(source).to_string(),
                at: Located::of(source, import.span()),
            })
            .collect();

        let declared_types = crate::types::declared_type_names(source, schema)
            .into_iter()
            .map(ToString::to_string)
            .collect();

        let qualified_uses = crate::types::qualified_type_uses(source, schema)
            .into_iter()
            .map(|(binding, name, span)| QualifiedUse {
                binding: binding.to_string(),
                name: name.to_string(),
                spelled: span.text(source).to_string(),
                at: Located::of(source, span),
            })
            .collect();

        ModuleSummary {
            path: path.to_string(),
            root,
            dependency_set: dependency_set.map(ToString::to_string),
            name,
            header: Located::of(source, header.span()),
            content_id: content_id(source.bytes()),
            imports,
            declared_types,
            qualified_uses,
        }
    }

    /// Whether this summary was derived from exactly these source bytes.
    ///
    /// A resolver handed a summary it did not derive must ask. A summary is a
    /// derived artifact, and a derived artifact that is trusted without being
    /// bound to its input is a way to make the source stop being the truth.
    pub fn describes(&self, bytes: &[u8]) -> bool {
        self.content_id == content_id(bytes)
    }

    /// The identity every diagnostic about this module carries.
    pub fn identity(&self) -> crate::ModuleIdentity {
        crate::ModuleIdentity::new(
            self.name.clone(),
            self.path.clone(),
            self.content_id.clone(),
        )
    }

    /// The module-set imports, which name modules rather than capabilities.
    pub fn module_imports(&self) -> impl Iterator<Item = &ImportSummary> {
        self.imports
            .iter()
            .filter(|import| import.kind != ImportKind::Capability)
    }
}

/// `sha256:<hex>` over the normalized source bytes.
fn content_id(bytes: &[u8]) -> String {
    let digest = tos_hash::sha256(bytes);
    let mut hex = [0u8; 64];
    tos_hash::hex(&digest, &mut hex);
    alloc::format!(
        "sha256:{}",
        core::str::from_utf8(&hex).expect("hex output is ASCII")
    )
}
